In [150]:
import numpy as np

In [151]:
N = 100
D = 2

In [152]:
X = np.random.rand(N,D)

In [153]:
print(X)
print(X.shape)

[[0.33796273 0.72803424]
 [0.17919888 0.34058941]
 [0.64061806 0.39219369]
 [0.66106507 0.79578061]
 [0.28520065 0.39897424]
 [0.3566783  0.884323  ]
 [0.59082672 0.94552081]
 [0.02103418 0.92153723]
 [0.16078196 0.46687378]
 [0.91845143 0.82156629]
 [0.46378884 0.98519181]
 [0.53713794 0.17154051]
 [0.54636806 0.10564628]
 [0.05395987 0.93700827]
 [0.08637979 0.56707383]
 [0.37211086 0.44261544]
 [0.60702154 0.31851077]
 [0.19905873 0.45661821]
 [0.97785503 0.62618736]
 [0.23030737 0.89860898]
 [0.2670936  0.418414  ]
 [0.64420067 0.43279405]
 [0.96617104 0.17437307]
 [0.71251189 0.73915503]
 [0.46624537 0.44142252]
 [0.72997646 0.15649961]
 [0.16730075 0.75872613]
 [0.51579161 0.63715529]
 [0.4909566  0.88629864]
 [0.6092473  0.01286665]
 [0.53063723 0.98785324]
 [0.43249085 0.56774299]
 [0.43254522 0.78637235]
 [0.11921326 0.79276041]
 [0.95703452 0.95960269]
 [0.5296009  0.17694947]
 [0.60446655 0.30867709]
 [0.64485513 0.45324802]
 [0.17820534 0.6902933 ]
 [0.8139656  0.27021589]


In [154]:
X[:50,:]

array([[0.33796273, 0.72803424],
       [0.17919888, 0.34058941],
       [0.64061806, 0.39219369],
       [0.66106507, 0.79578061],
       [0.28520065, 0.39897424],
       [0.3566783 , 0.884323  ],
       [0.59082672, 0.94552081],
       [0.02103418, 0.92153723],
       [0.16078196, 0.46687378],
       [0.91845143, 0.82156629],
       [0.46378884, 0.98519181],
       [0.53713794, 0.17154051],
       [0.54636806, 0.10564628],
       [0.05395987, 0.93700827],
       [0.08637979, 0.56707383],
       [0.37211086, 0.44261544],
       [0.60702154, 0.31851077],
       [0.19905873, 0.45661821],
       [0.97785503, 0.62618736],
       [0.23030737, 0.89860898],
       [0.2670936 , 0.418414  ],
       [0.64420067, 0.43279405],
       [0.96617104, 0.17437307],
       [0.71251189, 0.73915503],
       [0.46624537, 0.44142252],
       [0.72997646, 0.15649961],
       [0.16730075, 0.75872613],
       [0.51579161, 0.63715529],
       [0.4909566 , 0.88629864],
       [0.6092473 , 0.01286665],
       [0.

In [155]:
X[50:,:]

array([[0.36028816, 0.24171925],
       [0.50497255, 0.47421298],
       [0.37188659, 0.62322857],
       [0.15773624, 0.17358683],
       [0.06651417, 0.63571967],
       [0.87001253, 0.70803049],
       [0.71527693, 0.04106408],
       [0.1059593 , 0.62158748],
       [0.59974753, 0.45263189],
       [0.80916686, 0.53471701],
       [0.4007382 , 0.52937616],
       [0.18466378, 0.9698995 ],
       [0.57309248, 0.07311088],
       [0.64501331, 0.21752798],
       [0.89521756, 0.86165732],
       [0.799973  , 0.8110726 ],
       [0.73057914, 0.56274075],
       [0.40994103, 0.07373709],
       [0.02741123, 0.12909928],
       [0.74495828, 0.08328952],
       [0.64881124, 0.42985038],
       [0.78078362, 0.11000214],
       [0.30662189, 0.37708511],
       [0.32315393, 0.28242854],
       [0.18214171, 0.98265668],
       [0.56217934, 0.9164286 ],
       [0.11679548, 0.25509312],
       [0.19452139, 0.93596084],
       [0.90235317, 0.30778051],
       [0.68301045, 0.87912447],
       [0.

In [156]:
2*np.ones((50,D))

array([[2., 2.],
       [2., 2.],
       [2., 2.],
       [2., 2.],
       [2., 2.],
       [2., 2.],
       [2., 2.],
       [2., 2.],
       [2., 2.],
       [2., 2.],
       [2., 2.],
       [2., 2.],
       [2., 2.],
       [2., 2.],
       [2., 2.],
       [2., 2.],
       [2., 2.],
       [2., 2.],
       [2., 2.],
       [2., 2.],
       [2., 2.],
       [2., 2.],
       [2., 2.],
       [2., 2.],
       [2., 2.],
       [2., 2.],
       [2., 2.],
       [2., 2.],
       [2., 2.],
       [2., 2.],
       [2., 2.],
       [2., 2.],
       [2., 2.],
       [2., 2.],
       [2., 2.],
       [2., 2.],
       [2., 2.],
       [2., 2.],
       [2., 2.],
       [2., 2.],
       [2., 2.],
       [2., 2.],
       [2., 2.],
       [2., 2.],
       [2., 2.],
       [2., 2.],
       [2., 2.],
       [2., 2.],
       [2., 2.],
       [2., 2.]])

In [157]:
#first 50 rows are subtracted with 2 value 
X[:50,:] = X[:50,:] - 2*np.ones((50,D))

In [158]:
X[:50,:]

array([[-1.66203727, -1.27196576],
       [-1.82080112, -1.65941059],
       [-1.35938194, -1.60780631],
       [-1.33893493, -1.20421939],
       [-1.71479935, -1.60102576],
       [-1.6433217 , -1.115677  ],
       [-1.40917328, -1.05447919],
       [-1.97896582, -1.07846277],
       [-1.83921804, -1.53312622],
       [-1.08154857, -1.17843371],
       [-1.53621116, -1.01480819],
       [-1.46286206, -1.82845949],
       [-1.45363194, -1.89435372],
       [-1.94604013, -1.06299173],
       [-1.91362021, -1.43292617],
       [-1.62788914, -1.55738456],
       [-1.39297846, -1.68148923],
       [-1.80094127, -1.54338179],
       [-1.02214497, -1.37381264],
       [-1.76969263, -1.10139102],
       [-1.7329064 , -1.581586  ],
       [-1.35579933, -1.56720595],
       [-1.03382896, -1.82562693],
       [-1.28748811, -1.26084497],
       [-1.53375463, -1.55857748],
       [-1.27002354, -1.84350039],
       [-1.83269925, -1.24127387],
       [-1.48420839, -1.36284471],
       [-1.5090434 ,

In [159]:
print(X)
print(X.shape)

[[-1.66203727 -1.27196576]
 [-1.82080112 -1.65941059]
 [-1.35938194 -1.60780631]
 [-1.33893493 -1.20421939]
 [-1.71479935 -1.60102576]
 [-1.6433217  -1.115677  ]
 [-1.40917328 -1.05447919]
 [-1.97896582 -1.07846277]
 [-1.83921804 -1.53312622]
 [-1.08154857 -1.17843371]
 [-1.53621116 -1.01480819]
 [-1.46286206 -1.82845949]
 [-1.45363194 -1.89435372]
 [-1.94604013 -1.06299173]
 [-1.91362021 -1.43292617]
 [-1.62788914 -1.55738456]
 [-1.39297846 -1.68148923]
 [-1.80094127 -1.54338179]
 [-1.02214497 -1.37381264]
 [-1.76969263 -1.10139102]
 [-1.7329064  -1.581586  ]
 [-1.35579933 -1.56720595]
 [-1.03382896 -1.82562693]
 [-1.28748811 -1.26084497]
 [-1.53375463 -1.55857748]
 [-1.27002354 -1.84350039]
 [-1.83269925 -1.24127387]
 [-1.48420839 -1.36284471]
 [-1.5090434  -1.11370136]
 [-1.3907527  -1.98713335]
 [-1.46936277 -1.01214676]
 [-1.56750915 -1.43225701]
 [-1.56745478 -1.21362765]
 [-1.88078674 -1.20723959]
 [-1.04296548 -1.04039731]
 [-1.4703991  -1.82305053]
 [-1.39553345 -1.69132291]
 

In [160]:
#last 50 rows are added with 2 value 

X[50:,:] = X[50:,:] + 2*np.ones((50,D))  # last 50 rows are added with 2 value 

In [161]:
print(X)

[[-1.66203727 -1.27196576]
 [-1.82080112 -1.65941059]
 [-1.35938194 -1.60780631]
 [-1.33893493 -1.20421939]
 [-1.71479935 -1.60102576]
 [-1.6433217  -1.115677  ]
 [-1.40917328 -1.05447919]
 [-1.97896582 -1.07846277]
 [-1.83921804 -1.53312622]
 [-1.08154857 -1.17843371]
 [-1.53621116 -1.01480819]
 [-1.46286206 -1.82845949]
 [-1.45363194 -1.89435372]
 [-1.94604013 -1.06299173]
 [-1.91362021 -1.43292617]
 [-1.62788914 -1.55738456]
 [-1.39297846 -1.68148923]
 [-1.80094127 -1.54338179]
 [-1.02214497 -1.37381264]
 [-1.76969263 -1.10139102]
 [-1.7329064  -1.581586  ]
 [-1.35579933 -1.56720595]
 [-1.03382896 -1.82562693]
 [-1.28748811 -1.26084497]
 [-1.53375463 -1.55857748]
 [-1.27002354 -1.84350039]
 [-1.83269925 -1.24127387]
 [-1.48420839 -1.36284471]
 [-1.5090434  -1.11370136]
 [-1.3907527  -1.98713335]
 [-1.46936277 -1.01214676]
 [-1.56750915 -1.43225701]
 [-1.56745478 -1.21362765]
 [-1.88078674 -1.20723959]
 [-1.04296548 -1.04039731]
 [-1.4703991  -1.82305053]
 [-1.39553345 -1.69132291]
 

In [162]:
# first 50 rows are 0's & last 50 rows are 1's 
T = np.array([0]*50+[1]*50) # T= Targets
print(T)  
              

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


In [163]:
ones = np.ones((N,1))
print(ones)

[[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]


In [164]:
Xb = np.concatenate((X,ones),axis = 1) #  x is input & ones is bias

In [165]:
print(Xb)

[[-1.66203727 -1.27196576  1.        ]
 [-1.82080112 -1.65941059  1.        ]
 [-1.35938194 -1.60780631  1.        ]
 [-1.33893493 -1.20421939  1.        ]
 [-1.71479935 -1.60102576  1.        ]
 [-1.6433217  -1.115677    1.        ]
 [-1.40917328 -1.05447919  1.        ]
 [-1.97896582 -1.07846277  1.        ]
 [-1.83921804 -1.53312622  1.        ]
 [-1.08154857 -1.17843371  1.        ]
 [-1.53621116 -1.01480819  1.        ]
 [-1.46286206 -1.82845949  1.        ]
 [-1.45363194 -1.89435372  1.        ]
 [-1.94604013 -1.06299173  1.        ]
 [-1.91362021 -1.43292617  1.        ]
 [-1.62788914 -1.55738456  1.        ]
 [-1.39297846 -1.68148923  1.        ]
 [-1.80094127 -1.54338179  1.        ]
 [-1.02214497 -1.37381264  1.        ]
 [-1.76969263 -1.10139102  1.        ]
 [-1.7329064  -1.581586    1.        ]
 [-1.35579933 -1.56720595  1.        ]
 [-1.03382896 -1.82562693  1.        ]
 [-1.28748811 -1.26084497  1.        ]
 [-1.53375463 -1.55857748  1.        ]
 [-1.27002354 -1.84350039

In [166]:
# weights
w = np.random.randn(D+1) #randomly initialise weights

In [167]:
print(w)

[ 0.58619128 -0.38314121 -0.64886079]


In [168]:
#predictions
Z  = np.dot(Xb,w)
print(Z)

[-1.13579003 -1.08040994 -0.82970176 -0.97234669 -1.04064226 -1.1846998
 -1.07089144 -1.39570975 -1.13959052 -0.8313486  -1.16055953 -0.80581958
 -0.77516217 -1.3823366  -1.22159519 -1.00641699 -0.82116479 -1.11322368
 -0.72166901 -1.26425088 -1.05870462 -0.84315735 -0.55540939 -0.92049342
 -0.95077911 -0.68701653 -1.24758993 -0.99672883 -1.10674398 -0.70275521
 -1.12239329 -1.01896429 -1.10269834 -1.28881833 -0.86161897 -0.81231013
 -0.81889482 -0.85061046 -1.21497831 -0.68135223 -1.03181277 -0.68389612
 -0.76873053 -0.91862835 -0.98212267 -0.78568726 -1.08311181 -0.95637368
 -0.87721923 -0.87360325 -0.12417548 -0.12844068 -0.26354852 -0.21680531
 -0.44734103 -0.00404255  0.1607951  -0.41880401 -0.06461581  0.02669378
 -0.21067724 -0.50612082  0.06516937  0.05199659 -0.04812836 -0.0845788
 -0.03011071 -0.03070851 -0.27615568  0.16201574 -0.02712656  0.17278154
 -0.20749842 -0.16154065 -0.51248704 -0.26433759 -0.27203285 -0.48733908
  0.16826751 -0.1792147  -0.47812981 -0.08738568 -0.3

In [169]:
def sigmoid(z):
    return 1/(1+np.exp(-Z))

In [170]:
Y = sigmoid(Z)

In [171]:
print(Y)

[0.24309415 0.25342845 0.30370813 0.274413   0.26102609 0.23420821
 0.25523359 0.19849779 0.24239555 0.30335999 0.23856563 0.30878203
 0.31536348 0.20063399 0.22765585 0.26768164 0.30551646 0.24727038
 0.32702556 0.22024299 0.25755708 0.30087023 0.3646103  0.28485737
 0.27872816 0.33469709 0.22311761 0.26958506 0.24847841 0.33120165
 0.24556762 0.26522919 0.24923465 0.21605289 0.29700121 0.30739844
 0.30599831 0.29930481 0.22882138 0.33595957 0.26273281 0.33539229
 0.31675378 0.28523746 0.2724708  0.31309545 0.25291759 0.27760483
 0.29375435 0.29450509 0.46899596 0.4679339  0.4344916  0.44600999
 0.38999315 0.49898936 0.54011239 0.39680297 0.48385166 0.50667305
 0.44752464 0.37610334 0.51628658 0.51299622 0.48797023 0.4788679
 0.49247289 0.49232347 0.43139651 0.54041557 0.49321878 0.54308824
 0.44831072 0.45970243 0.37461069 0.43429773 0.4324081  0.38052061
 0.5419679  0.45531586 0.38269384 0.47816747 0.4047398  0.37079479
 0.39365847 0.50808599 0.54128684 0.44850856 0.41439689 0.41472

In [172]:
def cross_entropy_error(T,Y):
    E = 0
    for i in range(N):
        if T[i] == 1:
            E-=np.log(Y[i])
        else:
            E-=np.log(1 - Y[i])
    return E        
            

In [173]:
cross_entropy_error(T,Y)

55.165886573522364

In [174]:
w = np.array([0,4,4]) #bias,two columns values 4,4

In [175]:
Z = np.dot(Xb,w)
print(Z)

[-1.08786304 -2.63764235 -2.43122525 -0.81687756 -2.40410304 -0.46270801
 -0.21791676 -0.31385106 -2.1325049  -0.71373483 -0.05923276 -3.31383795
 -3.57741487 -0.25196692 -1.73170467 -2.22953825 -2.72595693 -2.17352714
 -1.49525055 -0.40556406 -2.32634401 -2.26882378 -3.30250772 -1.0433799
 -2.23430993 -3.37400157 -0.96509548 -1.45137883 -0.45480542 -3.9485334
 -0.04858703 -1.72902804 -0.85451061 -0.82895836 -0.16158924 -3.29220211
 -2.76529163 -2.18700792 -1.23882682 -2.91913643 -2.86033848 -3.37256332
 -2.65048664 -2.26765632 -1.79950506 -3.20989352 -3.09632714 -2.69898857
 -2.15049413 -2.23940958 12.96687699 13.89685194 14.49291429 12.6943473
 14.54287866 14.83212196 12.16425632 14.48634992 13.81052757 14.13886804
 14.11750463 15.87959799 12.29244353 12.87011192 15.44662928 15.24429039
 14.25096301 12.29494837 12.51639712 12.3331581  13.71940153 12.44000855
 13.50834043 13.12971414 15.93062672 15.6657144  13.02037249 15.74384336
 13.23112205 15.51649788 14.57559321 13.39584185 14.35

In [176]:
Y = sigmoid(Z)

In [177]:
print(Y)

[0.2520209  0.06675476 0.0808224  0.30642687 0.08286035 0.38634361
 0.44573538 0.42217502 0.10597743 0.32877411 0.48519614 0.03509951
 0.02718801 0.43733943 0.15036966 0.09712913 0.06145896 0.10215308
 0.18313496 0.39997625 0.08896454 0.09373809 0.03548526 0.26049837
 0.09671148 0.03311793 0.27585916 0.18978945 0.38821884 0.01891816
 0.48785563 0.15071195 0.29848751 0.30386537 0.45969036 0.03583967
 0.05922882 0.10092326 0.22464026 0.05121565 0.05414936 0.03316402
 0.06595902 0.09383731 0.14191132 0.0387951  0.04325901 0.06303306
 0.10428506 0.0962669  0.99999766 0.99999908 0.99999949 0.99999693
 0.99999952 0.99999964 0.99999479 0.99999949 0.999999   0.99999928
 0.99999926 0.99999987 0.99999541 0.99999743 0.9999998  0.99999976
 0.99999935 0.99999543 0.99999633 0.9999956  0.9999989  0.99999604
 0.99999864 0.99999801 0.99999988 0.99999984 0.99999779 0.99999985
 0.99999821 0.99999982 0.99999953 0.99999848 0.99999942 0.99999977
 0.99999984 0.99999948 0.99999859 0.99999939 0.99999985 0.9999

In [178]:
cross_entropy_error(T,Y)

10.639398047131225