In [107]:
import numpy as np


In [108]:
N = 100
D = 2

In [109]:
X = np.random.randn(N,D)
print(X)

[[ 0.2380272   2.66134911]
 [ 0.95313561  0.9171158 ]
 [ 0.48604677 -0.00805219]
 [ 0.54416748 -1.37386521]
 [ 0.35032829  0.03718381]
 [ 0.34075045  0.24012819]
 [-0.31764954 -0.26086676]
 [ 1.63591805 -1.11520528]
 [ 0.6002896  -0.35758434]
 [ 1.35825456  0.50284971]
 [ 1.14962908 -0.27782773]
 [ 1.44926465  1.54961274]
 [ 0.17161963 -2.30240459]
 [ 0.36693303 -0.83029352]
 [ 1.87987249 -0.74893357]
 [ 0.16627776 -1.08491997]
 [-0.88860941  0.27312323]
 [-0.87127319  1.01192744]
 [ 1.41580972 -0.1546592 ]
 [ 0.76350092 -1.50775473]
 [ 0.9838314  -0.8305039 ]
 [ 0.50024787  1.56565826]
 [-0.70242467  0.88748572]
 [ 0.83237925  0.51325848]
 [-1.86459382 -0.42710042]
 [ 0.46238932  0.77283023]
 [ 0.23202922  0.28058927]
 [ 0.26555802 -2.65404951]
 [-0.29134034 -0.11321322]
 [-0.12416182  1.00618111]
 [-0.79399119  0.67617583]
 [ 0.23858007  0.01368693]
 [-0.56462089 -0.78056578]
 [-1.02707557  1.01638279]
 [-0.56453699 -0.82906614]
 [ 2.88644899  0.49717956]
 [-0.61132906  0.27145854]
 

In [110]:
X[:50,:] = X[:50,:] - 2*np.ones((50,D))

In [111]:
print(X)

[[-1.7619728   0.66134911]
 [-1.04686439 -1.0828842 ]
 [-1.51395323 -2.00805219]
 [-1.45583252 -3.37386521]
 [-1.64967171 -1.96281619]
 [-1.65924955 -1.75987181]
 [-2.31764954 -2.26086676]
 [-0.36408195 -3.11520528]
 [-1.3997104  -2.35758434]
 [-0.64174544 -1.49715029]
 [-0.85037092 -2.27782773]
 [-0.55073535 -0.45038726]
 [-1.82838037 -4.30240459]
 [-1.63306697 -2.83029352]
 [-0.12012751 -2.74893357]
 [-1.83372224 -3.08491997]
 [-2.88860941 -1.72687677]
 [-2.87127319 -0.98807256]
 [-0.58419028 -2.1546592 ]
 [-1.23649908 -3.50775473]
 [-1.0161686  -2.8305039 ]
 [-1.49975213 -0.43434174]
 [-2.70242467 -1.11251428]
 [-1.16762075 -1.48674152]
 [-3.86459382 -2.42710042]
 [-1.53761068 -1.22716977]
 [-1.76797078 -1.71941073]
 [-1.73444198 -4.65404951]
 [-2.29134034 -2.11321322]
 [-2.12416182 -0.99381889]
 [-2.79399119 -1.32382417]
 [-1.76141993 -1.98631307]
 [-2.56462089 -2.78056578]
 [-3.02707557 -0.98361721]
 [-2.56453699 -2.82906614]
 [ 0.88644899 -1.50282044]
 [-2.61132906 -1.72854146]
 

In [112]:
X[50:,:] = X[50:,:] + 2*np.ones((50,D))


In [113]:
print(X)

[[-1.7619728   0.66134911]
 [-1.04686439 -1.0828842 ]
 [-1.51395323 -2.00805219]
 [-1.45583252 -3.37386521]
 [-1.64967171 -1.96281619]
 [-1.65924955 -1.75987181]
 [-2.31764954 -2.26086676]
 [-0.36408195 -3.11520528]
 [-1.3997104  -2.35758434]
 [-0.64174544 -1.49715029]
 [-0.85037092 -2.27782773]
 [-0.55073535 -0.45038726]
 [-1.82838037 -4.30240459]
 [-1.63306697 -2.83029352]
 [-0.12012751 -2.74893357]
 [-1.83372224 -3.08491997]
 [-2.88860941 -1.72687677]
 [-2.87127319 -0.98807256]
 [-0.58419028 -2.1546592 ]
 [-1.23649908 -3.50775473]
 [-1.0161686  -2.8305039 ]
 [-1.49975213 -0.43434174]
 [-2.70242467 -1.11251428]
 [-1.16762075 -1.48674152]
 [-3.86459382 -2.42710042]
 [-1.53761068 -1.22716977]
 [-1.76797078 -1.71941073]
 [-1.73444198 -4.65404951]
 [-2.29134034 -2.11321322]
 [-2.12416182 -0.99381889]
 [-2.79399119 -1.32382417]
 [-1.76141993 -1.98631307]
 [-2.56462089 -2.78056578]
 [-3.02707557 -0.98361721]
 [-2.56453699 -2.82906614]
 [ 0.88644899 -1.50282044]
 [-2.61132906 -1.72854146]
 

In [114]:
T = np.array([0]*50+[1]*50)
print(T)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


In [115]:
ones = np.ones((N,1))
print(ones)

[[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]


In [116]:
Xb = np.concatenate((X,ones),axis = 1)
print(Xb)

[[-1.7619728   0.66134911  1.        ]
 [-1.04686439 -1.0828842   1.        ]
 [-1.51395323 -2.00805219  1.        ]
 [-1.45583252 -3.37386521  1.        ]
 [-1.64967171 -1.96281619  1.        ]
 [-1.65924955 -1.75987181  1.        ]
 [-2.31764954 -2.26086676  1.        ]
 [-0.36408195 -3.11520528  1.        ]
 [-1.3997104  -2.35758434  1.        ]
 [-0.64174544 -1.49715029  1.        ]
 [-0.85037092 -2.27782773  1.        ]
 [-0.55073535 -0.45038726  1.        ]
 [-1.82838037 -4.30240459  1.        ]
 [-1.63306697 -2.83029352  1.        ]
 [-0.12012751 -2.74893357  1.        ]
 [-1.83372224 -3.08491997  1.        ]
 [-2.88860941 -1.72687677  1.        ]
 [-2.87127319 -0.98807256  1.        ]
 [-0.58419028 -2.1546592   1.        ]
 [-1.23649908 -3.50775473  1.        ]
 [-1.0161686  -2.8305039   1.        ]
 [-1.49975213 -0.43434174  1.        ]
 [-2.70242467 -1.11251428  1.        ]
 [-1.16762075 -1.48674152  1.        ]
 [-3.86459382 -2.42710042  1.        ]
 [-1.53761068 -1.22716977

In [117]:
w = np.random.randn(D+1)
print(w)

[-0.94340716 -0.51145453 -1.59871928]


In [118]:
z = np.dot(Xb,w)
print(z)

[-0.27471151 -0.05725388  0.85658243  1.5003022   0.96148406  0.86672304
  1.74409845  0.3380441   0.92757473 -0.22756774  0.36853205 -0.848799
  2.32667218  1.38949424 -0.0794356   1.70902372  2.00963447  1.61541461
  0.05442022  1.36185986  0.8076155   0.03830368  1.51976799  0.26322319
  3.28851772  0.4795152   0.94859743  2.41790042  1.64376009  0.91352337
  1.7142279   1.07892572  2.24289541  1.76012097  2.26762198 -1.66637728
  1.74889763  0.97202515  1.10231686  1.86821056  2.4873594   0.53448405
  2.8902312  -0.67586125  0.89588132  2.80010005  1.60213779  0.81703545
  2.07163441  0.2130399  -4.60916491 -2.86117532 -4.16347204 -4.36578676
 -5.27234394 -3.8422269  -4.62295757 -4.57562003 -5.04767245 -4.56343413
 -3.49160052 -6.23856452 -3.6958249  -5.42560154 -3.42728338 -5.43794549
 -5.67370328 -4.82598852 -3.78024026 -3.07465634 -4.0182968  -6.03554896
 -6.37157087 -5.45654042 -4.21512197 -4.98239832 -4.69258994 -4.7018293
 -2.69254511 -4.0773324  -4.08919005 -3.11053703 -5.28

In [119]:
sigmoid = 1/(1+np.exp(-z))

In [120]:
print(sigmoid)

[0.43175079 0.48569044 0.70194613 0.81761954 0.72341884 0.70406337
 0.8512069  0.58371533 0.71658299 0.44335232 0.59110422 0.29968486
 0.91106206 0.80051149 0.48015154 0.84670961 0.88180493 0.83416178
 0.5136017  0.79606181 0.69160115 0.50957475 0.82050431 0.56542846
 0.96403279 0.61763339 0.72083302 0.91818215 0.83804592 0.71372061
 0.84738386 0.74629063 0.90403594 0.85322481 0.90615977 0.15890778
 0.85181371 0.72552297 0.75069396 0.86625109 0.9232509  0.63052834
 0.94736141 0.33718565 0.71010238 0.94268123 0.83231696 0.69360669
 0.88811547 0.55305945 0.00986191 0.05410652 0.01531526 0.01254527
 0.00510537 0.02099552 0.00972813 0.0101949  0.00638326 0.01031861
 0.02955217 0.00194885 0.02422552 0.00438312 0.03145359 0.00432958
 0.00342336 0.00795484 0.0223082  0.04416485 0.01766587 0.00238647
 0.00170655 0.00425016 0.01455553 0.00681089 0.00907973 0.00899697
 0.06341469 0.01667003 0.01647677 0.0426747  0.00503137 0.03946624
 0.00186702 0.00545445 0.004768   0.02719024 0.01892929 0.0069

In [121]:
Y = sigmoid
print(Y)

[0.43175079 0.48569044 0.70194613 0.81761954 0.72341884 0.70406337
 0.8512069  0.58371533 0.71658299 0.44335232 0.59110422 0.29968486
 0.91106206 0.80051149 0.48015154 0.84670961 0.88180493 0.83416178
 0.5136017  0.79606181 0.69160115 0.50957475 0.82050431 0.56542846
 0.96403279 0.61763339 0.72083302 0.91818215 0.83804592 0.71372061
 0.84738386 0.74629063 0.90403594 0.85322481 0.90615977 0.15890778
 0.85181371 0.72552297 0.75069396 0.86625109 0.9232509  0.63052834
 0.94736141 0.33718565 0.71010238 0.94268123 0.83231696 0.69360669
 0.88811547 0.55305945 0.00986191 0.05410652 0.01531526 0.01254527
 0.00510537 0.02099552 0.00972813 0.0101949  0.00638326 0.01031861
 0.02955217 0.00194885 0.02422552 0.00438312 0.03145359 0.00432958
 0.00342336 0.00795484 0.0223082  0.04416485 0.01766587 0.00238647
 0.00170655 0.00425016 0.01455553 0.00681089 0.00907973 0.00899697
 0.06341469 0.01667003 0.01647677 0.0426747  0.00503137 0.03946624
 0.00186702 0.00545445 0.004768   0.02719024 0.01892929 0.0069

In [122]:
def cross_entropy_error(T,Y):
    E = 0
    for i in range(N):
        if T[i]==1:
            E-=np.log(Y[i])
        else:
            E-=np.log(1-Y[i])
    return E        

In [123]:
cross_entropy_error(T,Y)

300.3419593731118

In [124]:
G = T -Y
print(G)

[-0.43175079 -0.48569044 -0.70194613 -0.81761954 -0.72341884 -0.70406337
 -0.8512069  -0.58371533 -0.71658299 -0.44335232 -0.59110422 -0.29968486
 -0.91106206 -0.80051149 -0.48015154 -0.84670961 -0.88180493 -0.83416178
 -0.5136017  -0.79606181 -0.69160115 -0.50957475 -0.82050431 -0.56542846
 -0.96403279 -0.61763339 -0.72083302 -0.91818215 -0.83804592 -0.71372061
 -0.84738386 -0.74629063 -0.90403594 -0.85322481 -0.90615977 -0.15890778
 -0.85181371 -0.72552297 -0.75069396 -0.86625109 -0.9232509  -0.63052834
 -0.94736141 -0.33718565 -0.71010238 -0.94268123 -0.83231696 -0.69360669
 -0.88811547 -0.55305945  0.99013809  0.94589348  0.98468474  0.98745473
  0.99489463  0.97900448  0.99027187  0.9898051   0.99361674  0.98968139
  0.97044783  0.99805115  0.97577448  0.99561688  0.96854641  0.99567042
  0.99657664  0.99204516  0.9776918   0.95583515  0.98233413  0.99761353
  0.99829345  0.99574984  0.98544447  0.99318911  0.99092027  0.99100303
  0.93658531  0.98332997  0.98352323  0.9573253   0

In [128]:
learning_rate = 0.1

In [130]:
for i in range(100):
    if i % 10 == 0:
        print(cross_entropy_error(T,Y))
    # gradient descent formula    
    w = w+learning_rate*(np.dot(Xb.T,T-Y)- 0.1*w)    
    
    #recalculating sigmoid
    z = np.dot(Xb,w)
    #print(z)
    sigmoid = 1/(1+np.exp(-z))
    Y = sigmoid
    #print(Y)

0.28090459810968327
0.30422497779885377
0.32038533473819897
0.3309695431489723
0.3376616400619373
0.3418069720888789
0.34434637389260553
0.3458936313033813
0.34683449308025605
0.34740660720873495
