In [1]:
import numpy as np

In [2]:
N = 50
D = 2 

In [7]:
X = np.random.rand(N,D)
ones = np.ones((N,1))

In [8]:
X

array([[0.94908966, 0.1437566 ],
       [0.63972553, 0.70268877],
       [0.78863869, 0.37131274],
       [0.26289725, 0.83453668],
       [0.81387325, 0.84631541],
       [0.11684172, 0.60186718],
       [0.21721008, 0.16150311],
       [0.95842855, 0.30673442],
       [0.48382191, 0.80895558],
       [0.02688728, 0.13828026],
       [0.79945699, 0.35070172],
       [0.82532852, 0.51479429],
       [0.60318455, 0.838392  ],
       [0.30138086, 0.63019214],
       [0.65854963, 0.15419326],
       [0.65178134, 0.84261772],
       [0.78208492, 0.9702932 ],
       [0.42571675, 0.745987  ],
       [0.99087323, 0.15257739],
       [0.48840223, 0.0721582 ],
       [0.31147963, 0.37926488],
       [0.37901477, 0.08065452],
       [0.8034153 , 0.3697087 ],
       [0.32211037, 0.00823475],
       [0.47193837, 0.33380219],
       [0.82200567, 0.79419446],
       [0.50032124, 0.59089333],
       [0.68458881, 0.94040163],
       [0.16956874, 0.49947397],
       [0.69088784, 0.95972902],
       [0.

In [9]:
ones

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [13]:
xones = np.concatenate((ones,X),axis = 1)

In [15]:
xones

array([[1.        , 0.94908966, 0.1437566 ],
       [1.        , 0.63972553, 0.70268877],
       [1.        , 0.78863869, 0.37131274],
       [1.        , 0.26289725, 0.83453668],
       [1.        , 0.81387325, 0.84631541],
       [1.        , 0.11684172, 0.60186718],
       [1.        , 0.21721008, 0.16150311],
       [1.        , 0.95842855, 0.30673442],
       [1.        , 0.48382191, 0.80895558],
       [1.        , 0.02688728, 0.13828026],
       [1.        , 0.79945699, 0.35070172],
       [1.        , 0.82532852, 0.51479429],
       [1.        , 0.60318455, 0.838392  ],
       [1.        , 0.30138086, 0.63019214],
       [1.        , 0.65854963, 0.15419326],
       [1.        , 0.65178134, 0.84261772],
       [1.        , 0.78208492, 0.9702932 ],
       [1.        , 0.42571675, 0.745987  ],
       [1.        , 0.99087323, 0.15257739],
       [1.        , 0.48840223, 0.0721582 ],
       [1.        , 0.31147963, 0.37926488],
       [1.        , 0.37901477, 0.08065452],
       [1.

In [14]:
w = np.random.randn(D+1)

In [12]:
w

array([-0.11025213,  0.73495101,  0.23789171])

In [16]:
Y = np.dot(xones,w)

In [17]:
print(Y)

[0.77419037 1.40052171 1.04455808 1.68364822 1.44845786 1.54537404
 1.11578594 0.91246885 1.56285891 1.18028705 1.02172442 1.15361113
 1.53540431 1.48790896 0.91276053 1.51744543 1.57097512 1.5337141
 0.76328309 0.91687188 1.26410405 0.97303456 1.03657254 0.9350946
 1.15287893 1.39928182 1.36492564 1.58828941 1.43239213 1.60237467
 1.2965876  1.3731672  1.44509642 1.18488167 0.99864153 1.42631933
 1.57259978 1.2472224  1.16029903 1.03679014 1.50425351 1.30626146
 1.52697765 1.38988803 1.35419509 1.82964466 0.88169201 1.33627187
 1.42947701 1.5414374 ]


In [18]:
sigmoid = 1/1+np.exp(-Y)

In [19]:
print(sigmoid)

[1.46107693 1.24646835 1.35184727 1.18569528 1.23493231 1.2132321
 1.32765766 1.40153168 1.20953617 1.30719055 1.35997366 1.31549541
 1.2153686  1.22584441 1.40141458 1.21927132 1.20784241 1.21573292
 1.46613355 1.39976761 1.28249228 1.37793443 1.35466821 1.39254873
 1.3157265  1.24677413 1.25539967 1.20427474 1.23873715 1.20141765
 1.27346337 1.25330342 1.23572335 1.30578236 1.36837953 1.24019136
 1.20750501 1.2873017  1.31339245 1.35459104 1.22218309 1.27083068
 1.2171911  1.2491032  1.258155   1.16047058 1.41408169 1.26282369
 1.23943411 1.21407317]
